# 项目开发流程管理系统配置文件

# 阶段配置
phases:
  BASIC_DESIGN:
    focus_goals:
      - 业务逻辑设计
      - 系统架构设计
      - 数据库设计
      - 外部接口定义
    required_outputs:
      - 业务流程图
      - 系统架构图
      - ER图和表结构
      - API接口清单
    review_weights:
      业务完整性: 30
      数据库设计: 25
      架构合理性: 25
      接口定义: 20
    pass_score: 80
    max_iterations: 5
    rollback_triggers:
      - 数据库设计无法支持
      - 架构存在根本缺陷

  DETAIL_DESIGN:
    focus_goals:
      - 代码架构设计
      - 算法设计
      - 数据结构设计
      - 类设计
    required_outputs:
      - 类图
      - 算法伪代码
      - 数据结构定义
      - 时序图
    review_weights:
      类设计: 30
      数据结构: 25
      算法合理性: 25
      模块耦合: 20
    pass_score: 80
    max_iterations: 4
    rollback_triggers:
      - 数据库设计无法支持
      - 架构存在根本缺陷

  DEVELOPMENT:
    focus_goals:
      - 功能实现
      - 代码质量
      - 异常处理
      - 性能优化
    required_outputs:
      - 源代码
      - 配置文件
      - 数据库脚本
      - README文档
    review_weights:
      功能完整性: 35
      代码规范: 25
      异常处理: 20
      性能: 20
    pass_score: 85
    max_iterations: 4
    rollback_triggers:
      - 数据结构无法实现
      - 算法逻辑漏洞

  UNIT_TEST:
    focus_goals:
      - 单元测试覆盖
      - 边界测试
      - 异常测试
      - 测试质量
    required_outputs:
      - 测试用例
      - 测试代码
      - 覆盖率报告
      - 测试文档
    review_weights:
      覆盖率: 35
      边界测试: 30
      异常测试: 35
    pass_score: 90
    max_iterations: 3
    rollback_triggers:
      - 核心功能测试失败
      - 设计缺陷

  INTEGRATION_TEST:
    focus_goals:
      - 系统集成
      - 端到端测试
      - 性能测试
      - 稳定性测试
    required_outputs:
      - 集成测试用例
      - 性能报告
      - 部署文档
      - 最终验证报告
    review_weights:
      集成完整性: 40
      性能达标: 30
      稳定性: 30
    pass_score: 95
    max_iterations: 3

# 质量门禁配置
quality_gates:
  allow_rollback: true
  max_rollbacks_per_phase: 2
  total_rollbacks: 0
  force_forward_threshold: 3

# 系统配置
system:
  default_mode: "developer"
  output_format: "markdown"
  state_persistence: "json"
  log_level: "INFO"
